package formlogin;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author KURNIA
 */
public class Database_Customer extends javax.swing.JFrame {
private void kosongkan_form1(){
        Nama.setEditable(true);
        Nama.setText(null);
        Telpon.setText(null);
        Email.setText(null);
        Alamat.setText(null);
}
private void tampilkan_data1(){
        
        DefaultTableModel model1 = new DefaultTableModel();
        model1.addColumn("No.");
        model1.addColumn("Nama");
        model1.addColumn("No. Telpon");
        model1.addColumn("Email");
        model1.addColumn("Alamat");

 try{
        int no = 1;
        String sql = "Select * FROM customer";
        java.sql.Connection conn = (Connection)Konfig1.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while(res.next()){
            model1.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
        }
        tabelCustomer.setModel(model1);
        
    }catch (SQLException e){
        System.out.println("Error : "+e.getMessage());
    }
}

public Database_Customer() {
        initComponents();
        tampilkan_data1();
        kosongkan_form1();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Telpon = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelCustomer = new javax.swing.JTable();
        tbSimpan1 = new javax.swing.JButton();
        tbEdit1 = new javax.swing.JButton();
        tbHapus1 = new javax.swing.JButton();
        tbBatal1 = new javax.swing.JButton();
        tbKeluar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Swis721 BlkCn BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATA CUSTOMER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 150, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 60, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No.Telp");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 60, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 50, -1));

        Nama.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 200, -1));

        Telpon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(Telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, -1));

        Email.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 200, -1));

        Alamat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 200, 60));

        tabelCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelCustomer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, 90));

        tbSimpan1.setText("Simpan");
        tbSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSimpan1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbSimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        tbEdit1.setText("Edit");
        tbEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEdit1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        tbHapus1.setText("Hapus");
        tbHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapus1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 73, -1));

        tbBatal1.setText("Batal");
        tbBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBatal1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbBatal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        tbKeluar1.setText("Kembali");
        tbKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluar1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbKeluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formlogin/elegant-dark-background-with-golden-details_23-2148430347.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSimpan1ActionPerformed
        
        try{
            String sql = "INSERT INTO customer VALUES('"+Nama.getText()+"','"+Telpon.getText()+"','"+Email.getText()+"','"+Alamat.getText()+"')";
            java.sql.Connection conn = (Connection)Konfig1.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil..");
            tampilkan_data1();
            kosongkan_form1();

        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tbSimpan1ActionPerformed

    private void tbEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEdit1ActionPerformed

        try{
            String sql = "UPDATE customer SET Nama ="+Nama.getText()+"',No.Telpon = '"+Telpon.getText()+"',Email ='"+Email.getText()+"',Alamat ='"+Alamat.getText()+"' WHERE Nama = '"+Nama.getText()+"'";
            java.sql.Connection conn = (Connection)Konfig1.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil..");
         }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data1();
        kosongkan_form1();
    }//GEN-LAST:event_tbEdit1ActionPerformed

    private void tbHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapus1ActionPerformed
        
        try{
            String sql = "DELETE FROM customer WHERE Nama = '"+Nama.getText()+"'";
           java.sql.Connection conn = (Connection)Konfig1.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil..");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data1();
        kosongkan_form1(); 
        
    }//GEN-LAST:event_tbHapus1ActionPerformed

    private void tbBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBatal1ActionPerformed
        
        kosongkan_form1();
    }//GEN-LAST:event_tbBatal1ActionPerformed

    private void tbKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluar1ActionPerformed
   Form_Menu fmenu = new Form_Menu();
        fmenu.setVisible(true);
            dispose();
    }//GEN-LAST:event_tbKeluar1ActionPerformed

    private void tabelCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCustomerMouseClicked
        
        int baris = tabelCustomer.rowAtPoint(evt.getPoint());
        String nama = tabelCustomer.getValueAt(baris, 1).toString();
        Nama.setText(nama);
        
        String telpon = tabelCustomer.getValueAt(baris, 2).toString();
        Telpon.setText(telpon);
        
        String email = tabelCustomer.getValueAt(baris, 3).toString();
        Email.setText(email);
        
        String alamat = tabelCustomer.getValueAt(baris, 4).toString();
        Alamat.setText(alamat);
        
    }//GEN-LAST:event_tabelCustomerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Database_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Database_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Database_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Database_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Database_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Telpon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelCustomer;
    private javax.swing.JButton tbBatal1;
    private javax.swing.JButton tbEdit1;
    private javax.swing.JButton tbHapus1;
    private javax.swing.JButton tbKeluar1;
    private javax.swing.JButton tbSimpan1;
    // End of variables declaration//GEN-END:variables
}
